baseURL = "https://qwxlea.ml/"
languageCode = "en-us"
title = "QWxlea"
theme = "mycactus"
publishDir = "docs"

enableEmoji = true
enableRobotsTXT = true

copyright = "QWxleA" # cactus will use title if copyright is not set
#disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Everybody needs a place called home, even on the Internet. Just a place to store notes and snippets of things you find interesting. It doesn't have to be good, or smart, it just has to be yours. For me, that is this place, here."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://qwxlea.github.com/" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/qwxlea"
  [[params.social]]
   name = "mastodon"
   link = "https://ioc.exchange/@qwxlea"
  [[params.social]]
    name = "email"
    link = "qwxlea@gmail.com"  # no need for "mailto:" in the head

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
