#!/usr/bin/env bash
set -e

# BLOG=$HOME/Documents/QWxleA.github.io
# Hacky, but run from where the Makefile is
BLOG="$(cd "$(dirname "$0")" && cd .. && pwd )"
CONTENT="$BLOG/content"
#exporter puts everything into page/
PAGES="$CONTENT/page"
ASSETS="$BLOG/content/assets"
HUGOASSETS="$BLOG/static/assets"

STARTPAGE="$CONTENT/page/ Start here.md"
INDEXPAGE="$CONTENT/_index.md"

ZIP=$HOME/Downloads/publicExport.zip

#APPS
FIND=/opt/homebrew/bin/gfind

explode() {
    unzip -o -d $CONTENT $ZIP
    if [ -d "$ASSETS"  ]; then
        for a in $ASSETS/*; do 
            mv "$a" $HUGOASSETS
        done
        rmdir "$ASSETS"
    fi
    # FIX startpage (FIXMEFIXME about page)
    if [ -f "$STARTPAGE" ]; then
        mv "$STARTPAGE" "$INDEXPAGE"
        #FIXME relative path?
        gsed -i "s@ref \"@ref \"\/page\/@g" "$INDEXPAGE"
    fi
}

clean() {
    #running with scissors
    find "$PAGES" -iname "*.md" -exec rm "{}" \;
    if [[ $1 == "all" ]]; then
        # only remove images when told
        $FIND "$HUGOASSETS" -regextype posix-awk -regex "(.*.png|.*.jpg|.*.gif|.*.pdf)" -type f -delete
        # find "$HUGOASSETS" -iname "*" -exec rm "{}" \;
    fi
}

debug() {
    echo "Blog: $BLOG"
    echo "CONTENT: $CONTENT"
    echo "PAGES: $PAGES"
    echo "ASSETS: $ASSETS"
    echo "HUGOASSETS: $HUGOASSETS"
    echo "STARTPAGE: $STARTPAGE"
    echo "INDEXPAGE: $INDEXPAGE"
    echo "ZIP: $ZIP"
    exit
}

usage() { echo "Usage: $0 [-s <45|90>] [-p <string>]" 1>&2; exit 1; }

while getopts "cdlxz" o; do
    case "${o}" in
        c)
            clean
            ;;
        d)
            debug
            ;;
        l)
            unzip -v $ZIP
            exit
            ;;
        x)
            explode
            exit
            ;;
        z)
            clean all
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))